apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: kapp-controller.carvel.dev
spec:
  release:
  - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp: {}
          template:
          - ytt:
              paths:
              - config
              - config-release
          - kbld:
              paths:
              - '-'
              - .imgpkg/images.yml
      export:
      - imgpkgBundle:
<<<<<<< HEAD
          image: ysethiya/testkcontrol
=======
          image: ghcr.io/vmware-tanzu/carvel-kapp-controller-package-bundle
          useKbldImagesLock: false
>>>>>>> ad24bdc3e41219b176f88280a469e9fd21979339
        includePaths:
        - config
        - config-release
        - .imgpkg/images.yml
