#@data/values-schema
---
#@schema/desc "The namespace in which to deploy kapp-controller"
namespace: kapp-controller
#@schema/desc "Whether to create namespace specified for kapp-controller"
create_namespace: true

packaging_global_namespace: kapp-controller-packaging-global
create_packaging_namespace: true
#! clusters version 1.19 and below should disable APIPriorityAndFairness by setting the below to false
enable_api_priority_and_fairness: true

dangerous_enable_pprof: false

#! comma separated list of cipher suites - empty for language defaults
tls_cipher_suites: ""

api_port: 10350

