name: Run Go Vulnerability Checker

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scan-develop-branch:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.6"
      - name: Build the kapp-controller artifacts
        run: |
          ./hack/install-deps.sh
          ./hack/build.sh

          # docker image
          docker buildx build -t docker.io/carvel/kapp-controller:${{ github.sha }} .

          # kctrl
          cd cli
          ./hack/build.sh
          mv ./kctrl ../
      - name: Install govulnchecker
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run Go Vulnerability Checker
        run:  |
          export PATH=$PATH:$GOPATH/bin
          govulncheck ./...
